loading_dir: results/tox21_ptree/edge/cistrans_advanced

config_files:
  - configs/add_test_set.yaml
  - configs/use_separate_inv.yaml
  - configs/chem/cis_trans.yaml
  - configs/datasets/tox21.yaml
  - configs/models/ptree_inv.yaml
  - configs/general.yaml

n_best: 3