data:
  dataset:
    mask_chiral_tags: true
    type: rs
  loader:
    general:
      batch_size: 32
      n_neighbors_in_circle: 3
      num_workers: 0
      precompute_pos_enc:
      - RWSE
    test: {}
    train: {}
    val: {}
model:
  head:
    n_layer: 3
    pool_function: add
    type: san_head
  hidden_dim: 128
  mode: custom
  modules:
    0:
      parameter:
        edge_type: linear
        node_type: linear+RWSE
        rwse_params:
          dim_pos_enc: 28
          norm_type: batchnorm
      type: graph_embedding
    1:
      parameter:
        local_model: chienn
        local_model_params: {}
      times: 5
      type: gps_layer
  out_dim: 1
optimizer:
  base_learning_rate: 0.001
  type: adam_w
  weight_decay: 1.0e-05
scheduler:
  max_epochs: 100
  num_warmup_epochs: 10
  type: cosine_with_warmup
training:
  clip_grad_norm: true
  loss_function: cross_entropy
  n_max_epochs: 2
  optimization_metric: accuracy
  task_type: classification
