loading_dir: results/bace_ptree/vertex/cyclic_light

config_files:
  - configs/add_test_set.yaml
  - configs/chem/cyclic_trees_light.yaml
  - configs/add_rwse.yaml
  - configs/vertex_mode.yaml
  - configs/datasets/bace.yaml
  - configs/models/ptree_circle.yaml
  - configs/general.yaml

n_best: 3
