loading_dir: results/tox21_ptree/vertex/cyclic_minimal

config_files:
  - configs/add_test_set.yaml
  - configs/chem/cyclic_trees_minimal.yaml
  - configs/vertex_mode.yaml
  - configs/datasets/tox21.yaml
  - configs/models/ptree_circle.yaml
  - configs/general.yaml

n_best: 3
