output_dir: results/ez_ptree

config_files:
  - configs/hyper_param_opt/epoch_reduction.yaml
  - configs/datasets/ez_dataset.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

search_space:
  model:
    modules:
      1:
        times: tune.randint(1,6)

hyper_settings:
  scheduler:
    grace_period: 2
    reduction_factor: 3
    brackets: 1
  max_concurrent_trials: 2
  num_samples: 4 # set to this as this optimization is quite simplistic