output_dir: results/rs_ptree/vertex_selective_e

config_files:
  - configs/hyper_param_opt/subsetting.yaml
  - configs/hyper_param_opt/epoch_reduction.yaml
  - configs/vertex_mode.yaml
  - configs/chem/tetra_selective.yaml
  - configs/datasets/rs_dataset.yaml
  - configs/models/ptree_e.yaml
  - configs/general.yaml

search_space:
  model:
    modules:
      1:
        times: tune.randint(1,6)

hyper_settings:
  scheduler:
    grace_period: 2
    reduction_factor: 3
    brackets: 1
  max_concurrent_trials: 2
  num_samples: 6 # set to this as this optimization is quite simplistic
  stopper:
    num_results: 5
    metric_threshold: 0.95