data:
  dataset:
    graph_mode: edge
    transformation_mode: permutation_tree
    transformation_parameters:
      k: 4
      use_new_inv: True

model:
  mode: custom
  hidden_dim: 128
  modules:
    0:
      type: graph_embedding
      parameter:
        node_type: linear
        edge_type: linear
    1:
      type: gps_layer
      parameter:
        local_model: permutation_tree
        local_model_params:
          k: 4
          use_separate_inv: True
          apply_p_elu: False
      times: 5
  head:
    type: san_head
    n_layer: 3
    pool_function: add