loading_dir: results/bace_ptree/edge/cistrans_rwse

config_files:
  - configs/add_test_set.yaml
  - configs/chem/cis_trans.yaml
  - configs/add_rwse.yaml
  - configs/datasets/bace.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 3