loading_dir: results/rs_ptree/vertex_default_e

config_files:
  - configs/add_test_set.yaml
  - configs/hyper_param_opt/epoch_reduction.yaml
  - configs/vertex_mode.yaml
  - configs/datasets/rs_dataset.yaml
  - configs/models/ptree_e.yaml
  - configs/general.yaml

n_best: 2