loading_dir: results/rs_ptree/default

config_files:
  - configs/add_test_set.yaml
  - configs/hyper_param_opt/epoch_reduction.yaml
  - configs/datasets/rs_dataset.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 2