loading_dir: results/rs_ptree/selective

config_files:
  - configs/add_test_set.yaml
  - configs/chem/tetra_selective.yaml
  - configs/datasets/rs_dataset.yaml
  - configs/models/ptree_default.yaml
  - configs/general.yaml

n_best: 2