data:
  dataset:
    type: rs
    mask_chiral_tasks: True
  loader:
    general:
      n_neighbors_in_circle: 3
      batch_size: 32
      num_workers: 0
    train:
      sampler: single_conformer_sampler
    val:
      sampler: full_batch
    test:
      sampler: full_batch

training:
  loss_function: cross_entropy
  optimization_metric: accuracy
  optimization_metric_mode: max
  task_type: classification

model:
  out_dim: 1